---
title: "Day 25 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

I'm not going to try to parse the input


```{r}
turing<-function(reps){
  tape<-dict()
  counter<-1
  sta<-"A"
  pos<-0
  while(counter<=reps){
    if(!tape$has(pos)){tape$set(pos,0)}
    ### This is my input
    switch(sta,
           "A"={
             if(tape$get(pos)==0){
               tape$set(pos,1)
               pos<-pos+1
               sta<-"B"
             }else{
               tape$set(pos,0)
               pos<-pos-1
               sta<-"F"}},
           "B"={
             if(tape$get(pos)==0){
               tape$set(pos,0)
               pos<-pos+1
               sta<-"C"
             }else{
               tape$set(pos,0)
               pos<-pos+1
               sta<-"D"}},
           "C"={
             if(tape$get(pos)==0){
               tape$set(pos,1)
               pos<-pos-1
               sta<-"D"
             }else{
               tape$set(pos,1)
               pos<-pos+1
               sta<-"E"}},
           "D"={
             if(tape$get(pos)==0){
               tape$set(pos,0)
               pos<-pos-1
               sta<-"E"
             }else{
               tape$set(pos,0)
               pos<-pos-1
               sta<-"D"}},
           "E"={
             if(tape$get(pos)==0){
               tape$set(pos,0)
               pos<-pos+1
               sta<-"A"
             }else{
               tape$set(pos,1)
               pos<-pos+1
               sta<-"C"}},
           "F"={
             if(tape$get(pos)==0){
               tape$set(pos,1)
               pos<-pos-1
               sta<-"A"
             }else{
               tape$set(pos,1)
               pos<-pos+1
               sta<-"A"}},
           cat("State Problem\n"))
    counter<-counter+1}
  ### add all of the values
checksum<-sum(unlist(tape$values()))
checksum}
```


```{r}
turing(12794428)
```

