---
title: "Day 15 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}
robotduel<-function(a,b,turns){
  itsatie<-0
  for(i in 1:turns){
    ## calculate next values
    a<-(16807*a)%%2147483647
    b<-(48271*b)%%2147483647
    ## the final 16 is mod 65536, so those are the only ones to stay interested in
    if(a%%65536==b%%65536){itsatie<-itsatie+1}
    }
  itsatie}

```

```{r}
part1<-robotduel(65,8921,40000000)
part1
```
```{r}
longrobotduel<-function(a,b,turns){
  itsatie<-0
  for(i in 1:turns){
    ##generate the first/next a
    a<-(16807*a)%%2147483647
    ##keep generating a until something is divisible by 4
    while(a%%4!=0){
    a<-(16807*a)%%2147483647}
    ##generate the first/next b
    b<-(48271*b)%%2147483647
    ## keep generating until b is divisible by 8
    while(b%%8!=0){
    b<-(48271*b)%%2147483647}
    ##compare
    if(a%%65536==b%%65536){itsatie<-itsatie+1}}
  itsatie}

```


```{r}
part2<-longrobotduel(65,8921,5000000)
part2
```

