---
title: "Day 9 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}
input<-read_lines("Day9Sample.txt")
```

## Part 1
Function that does three things -
1.  remove the characters after a !.

2.  remove everything from a "<" to the first available ">"

3.  count groups

```{r}
streamscore<-function(st){
  ### remove characters after a !
  st<-str_replace_all(st,"!.","")
  ### remove garbage
  st<-str_replace_all(st,"<(.*?)>","")
  ### count score
  score<-0
  glevel<-0
  for(i in 1:nchar(st)){
    x<-str_sub(st,i,i)
    if(x=="{"){
      glevel<-glevel+1
    }else if(x=="}"){
      score<-score+glevel
      glevel<-glevel-1}}
score}
```

```{r}
part1<-sapply(input,streamscore)
part1
```

## Part 2

To count the garbage a function that does three and a half things:
1.  remove the characters after a !.
2.  find the first available "<" and the first ">"
3.  count the characters between the two
3.5.  drop everything before the ">" and repeat with the part of the string that remains

```{r}
garbagecounter<-function(st){
  ### remove characters after a !
  st<-str_replace_all(st,"!.","")
  ### create the garbage counter
  gc<-0
  while(str_detect(st,">")&nchar(st)>0){
    ### find the first lessthan
    lt<-str_locate(st,"<")[1]
    ### find the first greaterthan
    gt<-str_locate(st,">")[1]
    ### add the points between them
    gc<-gc+(gt-lt-1)
    ### start over with everything to the right of the greater than
    st<-str_sub(st,gt+1)}
gc}
```


```{r}
part2<-sapply(input,garbagecounter)
part2
```