---
title: "Day 13 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}
input<-read_lines("Day13Sample.txt")
scanners<-list()
### create the scanners as list of vectors of c(depth,length)
for(i in 1:length(input)){
  s<-as.numeric(unlist(str_split((str_remove_all(input[i],":"))," ")))
  scanners<-c(scanners,list(s))}
```
## Part 1
Create a function to say whether or not you were caught

```{r}
severitymeasure<-function(starting=0,scnrs=scanners){
### set severity to 0
    severity<-0
  for(i in 1:length(scanners)){
    s<-scanners[[i]]
    ### each scanner is on a cycle of 2*(scannerlength-1)
    ### a collision will happen if it is at 0 on that cycle - offset of by when the start is.
    if((starting+s[1])%%(2*(s[2]-1))==0){
      ### if there's a collision, add the severity (depth*length) to the severity counter
      severity<-severity+prod(s)}}
  severity}
```

```{r}
severitymeasure(0,scanners)
part1<-part1
```

## Part 2
So - there's the right way and there's BRUTE FORCE!!  
```{r}
catchme<-function(starting=0,scnrs=scanners){
  caught<-FALSE
  i<-1
  while(i<=length(scanners)&&!caught){
    ### if there's a collision, mark as TRUE.  Stop
    s<-scanners[[i]]
    if((starting+s[1])%%(2*(s[2]-1))==0){
      caught<-TRUE
      break}
    i<-i+1}
caught}
```



```{r}
i<-0
keepgoing<-TRUE
while(keepgoing){
  ### start at time=1 & keep going until caught is FALSE
  x<-catchme(i,scanners)
  if(!x){keepgoing=FALSE
  }else{
    i<-i+1}}
part2<-i
part2
```
